{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.pblop",
    "module": "twitch4j-util",
    "version": "expose-autojoin-own-channel-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        },
        {
          "group": "commons-configuration",
          "module": "commons-configuration",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "com.bucket4j",
          "module": "bucket4j_jdk8-core",
          "version": {
            "requires": "8.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.philippheuer.credentialmanager",
          "module": "credentialmanager",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-slf4j",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-okhttp",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-hystrix",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "com.neovisionaries",
          "module": "nv-websocket-client",
          "version": {
            "requires": "2.14"
          }
        },
        {
          "group": "com.github.tony19",
          "module": "named-regexp",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.netflix.hystrix",
          "module": "hystrix-core",
          "version": {
            "requires": "1.5.18"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.19.0"
          }
        },
        {
          "group": "io.github.xanthic.cache",
          "module": "cache-bom",
          "version": {
            "requires": "0.7.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.github.philippheuer.events4j",
          "module": "events4j-bom",
          "version": {
            "requires": "0.12.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.20.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-slf4j",
          "version": {
            "requires": "13.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-okhttp",
          "version": {
            "requires": "13.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson",
          "version": {
            "requires": "13.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-hystrix",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "files": [
        {
          "name": "twitch4j-util-expose-autojoin-own-channel-SNAPSHOT.jar",
          "url": "twitch4j-util-expose-autojoin-own-channel-SNAPSHOT.jar",
          "size": 18044,
          "sha512": "0cfee9ff30284578ce44a8320a39ce196ed72068b1a3291cf547ac2911baee0ec78ba28b086b49f8f17e427f9715351d13f3424299469b96983031fe917078b2",
          "sha256": "900ffe70f123d8199b2aedd3b50a135476ef0f74c0794e98e9839ad92c65b0a1",
          "sha1": "cf2a4da888e07bdd4ae4ecba964cd7263b6c5859",
          "md5": "2b474d6fafa8b88bb5b674ac1fca2248"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        },
        {
          "group": "commons-configuration",
          "module": "commons-configuration",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "com.bucket4j",
          "module": "bucket4j_jdk8-core",
          "version": {
            "requires": "8.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.philippheuer.credentialmanager",
          "module": "credentialmanager",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-slf4j",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-okhttp",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-hystrix",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "com.neovisionaries",
          "module": "nv-websocket-client",
          "version": {
            "requires": "2.14"
          }
        },
        {
          "group": "com.github.tony19",
          "module": "named-regexp",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.netflix.hystrix",
          "module": "hystrix-core",
          "version": {
            "requires": "1.5.18"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.19.0"
          }
        },
        {
          "group": "io.github.xanthic.cache",
          "module": "cache-bom",
          "version": {
            "requires": "0.7.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.github.philippheuer.events4j",
          "module": "events4j-bom",
          "version": {
            "requires": "0.12.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.20.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-slf4j",
          "version": {
            "requires": "13.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-okhttp",
          "version": {
            "requires": "13.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson",
          "version": {
            "requires": "13.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-hystrix",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "files": [
        {
          "name": "twitch4j-util-expose-autojoin-own-channel-SNAPSHOT.jar",
          "url": "twitch4j-util-expose-autojoin-own-channel-SNAPSHOT.jar",
          "size": 18044,
          "sha512": "0cfee9ff30284578ce44a8320a39ce196ed72068b1a3291cf547ac2911baee0ec78ba28b086b49f8f17e427f9715351d13f3424299469b96983031fe917078b2",
          "sha256": "900ffe70f123d8199b2aedd3b50a135476ef0f74c0794e98e9839ad92c65b0a1",
          "sha1": "cf2a4da888e07bdd4ae4ecba964cd7263b6c5859",
          "md5": "2b474d6fafa8b88bb5b674ac1fca2248"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "twitch4j-util-expose-autojoin-own-channel-SNAPSHOT-sources.jar",
          "url": "twitch4j-util-expose-autojoin-own-channel-SNAPSHOT-sources.jar",
          "size": 10388,
          "sha512": "a741ce2954a057554c92d18a8a5dc53660c80124da29ebdeaf0a18981e8be6d510e7747fad1a81c17b30898c7fbb35b1f724875aa099466c274ac7992787297f",
          "sha256": "a18ec0abac92dfe52eddb21d05f94f31178851b0a95569d0bc6ef952d553c877",
          "sha1": "ed6e531f73a8447e8a7612e22cdc120a18a2182e",
          "md5": "da383a6724616eb1f2a72974b783370c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "twitch4j-util-expose-autojoin-own-channel-SNAPSHOT-javadoc.jar",
          "url": "twitch4j-util-expose-autojoin-own-channel-SNAPSHOT-javadoc.jar",
          "size": 137556,
          "sha512": "0c92ea47c19da3f9723f60c6a88fe9b50efcbafc8c42e189b7787e70ec554209873ab3e5f347ee9ab4ffc3e8d6ccab970cd64ae1551589e626a54a86ab18ffe4",
          "sha256": "d8ab386eb5474a5444ea456b495dc7284633ed34eb2e6b7cbd7cf28d388eccb8",
          "sha1": "d5245b2c1347cfd817517d2e702d847ff45feecc",
          "md5": "f98b7250e42881a04894093251ddb28e"
        }
      ]
    }
  ]
}
