{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.pblop",
    "module": "twitch4j-chat",
    "version": "expose-autojoin-own-channel-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        },
        {
          "group": "commons-configuration",
          "module": "commons-configuration",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "com.bucket4j",
          "module": "bucket4j_jdk8-core",
          "version": {
            "requires": "8.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.philippheuer.credentialmanager",
          "module": "credentialmanager",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-slf4j",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-okhttp",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-hystrix",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "com.neovisionaries",
          "module": "nv-websocket-client",
          "version": {
            "requires": "2.14"
          }
        },
        {
          "group": "com.github.tony19",
          "module": "named-regexp",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.netflix.hystrix",
          "module": "hystrix-core",
          "version": {
            "requires": "1.5.18"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.19.0"
          }
        },
        {
          "group": "io.github.xanthic.cache",
          "module": "cache-bom",
          "version": {
            "requires": "0.7.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.github.philippheuer.events4j",
          "module": "events4j-bom",
          "version": {
            "requires": "0.12.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.20.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.bucket4j",
          "module": "bucket4j_jdk8-core"
        },
        {
          "group": "io.github.xanthic.cache",
          "module": "cache-provider-caffeine"
        },
        {
          "group": "com.github.tony19",
          "module": "named-regexp"
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-common",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-auth",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-client-websocket",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-slf4j",
          "version": {
            "requires": "13.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-okhttp",
          "version": {
            "requires": "13.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson",
          "version": {
            "requires": "13.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-hystrix",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "files": [
        {
          "name": "twitch4j-chat-expose-autojoin-own-channel-SNAPSHOT.jar",
          "url": "twitch4j-chat-expose-autojoin-own-channel-SNAPSHOT.jar",
          "size": 181727,
          "sha512": "a5aceca8de4c8c3971b6715678c85745d0530eb891f74382057b9ce872a8f492ff46a5c137d4a80b25f81debd59813ce059e08629ca56d1e83005f43fa5a5ddb",
          "sha256": "b670f34901a72fe18c78ecdb48096c95e76f1dfd0424a5b4139418b5cedf4a00",
          "sha1": "edbf09da6da8b8eef00adb394a91e8cd58cd5942",
          "md5": "553ebf972b22cd88224bd3ae3e32e6aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        },
        {
          "group": "commons-configuration",
          "module": "commons-configuration",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "com.bucket4j",
          "module": "bucket4j_jdk8-core",
          "version": {
            "requires": "8.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.philippheuer.credentialmanager",
          "module": "credentialmanager",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-slf4j",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-okhttp",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-hystrix",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "com.neovisionaries",
          "module": "nv-websocket-client",
          "version": {
            "requires": "2.14"
          }
        },
        {
          "group": "com.github.tony19",
          "module": "named-regexp",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.netflix.hystrix",
          "module": "hystrix-core",
          "version": {
            "requires": "1.5.18"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.19.0"
          }
        },
        {
          "group": "io.github.xanthic.cache",
          "module": "cache-bom",
          "version": {
            "requires": "0.7.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.github.philippheuer.events4j",
          "module": "events4j-bom",
          "version": {
            "requires": "0.12.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.20.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.bucket4j",
          "module": "bucket4j_jdk8-core"
        },
        {
          "group": "io.github.xanthic.cache",
          "module": "cache-provider-caffeine"
        },
        {
          "group": "com.github.tony19",
          "module": "named-regexp"
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-common",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-auth",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-client-websocket",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-slf4j",
          "version": {
            "requires": "13.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-okhttp",
          "version": {
            "requires": "13.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson",
          "version": {
            "requires": "13.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-hystrix",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "files": [
        {
          "name": "twitch4j-chat-expose-autojoin-own-channel-SNAPSHOT.jar",
          "url": "twitch4j-chat-expose-autojoin-own-channel-SNAPSHOT.jar",
          "size": 181727,
          "sha512": "a5aceca8de4c8c3971b6715678c85745d0530eb891f74382057b9ce872a8f492ff46a5c137d4a80b25f81debd59813ce059e08629ca56d1e83005f43fa5a5ddb",
          "sha256": "b670f34901a72fe18c78ecdb48096c95e76f1dfd0424a5b4139418b5cedf4a00",
          "sha1": "edbf09da6da8b8eef00adb394a91e8cd58cd5942",
          "md5": "553ebf972b22cd88224bd3ae3e32e6aa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "twitch4j-chat-expose-autojoin-own-channel-SNAPSHOT-sources.jar",
          "url": "twitch4j-chat-expose-autojoin-own-channel-SNAPSHOT-sources.jar",
          "size": 92025,
          "sha512": "3a9c40b4fd0920a3f9f15c21f36f5d4ac80310a1fd24e1bd3ef36c4d262bf6e7b4eebbae37c744708ff062923b35a41a959f06353082ae6b78b0102d7b5bd7ef",
          "sha256": "2705ab5b01f8ffe7ba0067425b6374a841da7e387b4556e058ec71bc02c4760e",
          "sha1": "d7ca9cc3b75218ca92182d37c15f1654e23b48f3",
          "md5": "a7d8854b75c291210f8ca054727f0693"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "twitch4j-chat-expose-autojoin-own-channel-SNAPSHOT-javadoc.jar",
          "url": "twitch4j-chat-expose-autojoin-own-channel-SNAPSHOT-javadoc.jar",
          "size": 500415,
          "sha512": "6af7af2405e5f99003910ed85462189d63091007338774b023c64914a008e63b485fdb4654141e6a9d6cc8ef50883c2f841b928cf031f32eccac7f6a19d172ad",
          "sha256": "7cd2bd572e11b8cb04eb6cfe8ba807af65307836fcd0260175d6deb0bbe58424",
          "sha1": "7235c21edf69f3b979de47a21c2468107dc7e277",
          "md5": "cca74f7db6182873cba70f2a2415c226"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "twitch4j-chat-expose-autojoin-own-channel-SNAPSHOT-all.jar",
          "url": "twitch4j-chat-expose-autojoin-own-channel-SNAPSHOT-all.jar",
          "size": 12481203,
          "sha512": "d594a83b7dea7c3e05bdb0cf4cbbb019c96395f15855ad57bd006a45cf42a7109534888f8559dbbe91b33c59c61a44d8cf8eaa39c7e1311f4756bc2f7f926c14",
          "sha256": "a593d8a516c1b35c60ffafc99ae27bc2f83cea1023b36d5cb3676daeaacccc53",
          "sha1": "60182170483919ec96a30f4e0b4fb2197bf25110",
          "md5": "ef4410a956e705e102814288f1ad6999"
        }
      ]
    }
  ]
}
