{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.pblop",
    "module": "twitch4j-extensions",
    "version": "expose-autojoin-own-channel-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        },
        {
          "group": "commons-configuration",
          "module": "commons-configuration",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "com.bucket4j",
          "module": "bucket4j_jdk8-core",
          "version": {
            "requires": "8.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.philippheuer.credentialmanager",
          "module": "credentialmanager",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-slf4j",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-okhttp",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-hystrix",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "com.neovisionaries",
          "module": "nv-websocket-client",
          "version": {
            "requires": "2.14"
          }
        },
        {
          "group": "com.github.tony19",
          "module": "named-regexp",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.netflix.hystrix",
          "module": "hystrix-core",
          "version": {
            "requires": "1.5.18"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.19.0"
          }
        },
        {
          "group": "io.github.xanthic.cache",
          "module": "cache-bom",
          "version": {
            "requires": "0.7.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.github.philippheuer.events4j",
          "module": "events4j-bom",
          "version": {
            "requires": "0.12.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.20.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-okhttp"
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson"
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-slf4j"
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-hystrix"
        },
        {
          "group": "commons-configuration",
          "module": "commons-configuration"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310"
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-common",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-helix",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-slf4j",
          "version": {
            "requires": "13.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-okhttp",
          "version": {
            "requires": "13.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson",
          "version": {
            "requires": "13.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-hystrix",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "files": [
        {
          "name": "twitch4j-extensions-expose-autojoin-own-channel-SNAPSHOT.jar",
          "url": "twitch4j-extensions-expose-autojoin-own-channel-SNAPSHOT.jar",
          "size": 50204,
          "sha512": "59dfeedc4652f5896117487a1dbc2dcef8723a07a56abeaedd9ac3ab15b2b4e15c9f33fd63a2d19971b9abdf70cb8d8fa912696c01bb90a69f870c98ba83d802",
          "sha256": "b17c1343380e912f4cc986777bf4b93b618e94005563930f15ae4e34fc3258e7",
          "sha1": "4af18a18ca1dcf8c2f3b37cd19ac6861fbc3e141",
          "md5": "633e0a71f87edd9a24e9e7f0e56745a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        },
        {
          "group": "commons-configuration",
          "module": "commons-configuration",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "com.bucket4j",
          "module": "bucket4j_jdk8-core",
          "version": {
            "requires": "8.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.philippheuer.credentialmanager",
          "module": "credentialmanager",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-slf4j",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-okhttp",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-hystrix",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "com.neovisionaries",
          "module": "nv-websocket-client",
          "version": {
            "requires": "2.14"
          }
        },
        {
          "group": "com.github.tony19",
          "module": "named-regexp",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.netflix.hystrix",
          "module": "hystrix-core",
          "version": {
            "requires": "1.5.18"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.19.0"
          }
        },
        {
          "group": "io.github.xanthic.cache",
          "module": "cache-bom",
          "version": {
            "requires": "0.7.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.github.philippheuer.events4j",
          "module": "events4j-bom",
          "version": {
            "requires": "0.12.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.20.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-okhttp"
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson"
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-slf4j"
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-hystrix"
        },
        {
          "group": "commons-configuration",
          "module": "commons-configuration"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310"
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-common",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-helix",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-slf4j",
          "version": {
            "requires": "13.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-okhttp",
          "version": {
            "requires": "13.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson",
          "version": {
            "requires": "13.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-hystrix",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "files": [
        {
          "name": "twitch4j-extensions-expose-autojoin-own-channel-SNAPSHOT.jar",
          "url": "twitch4j-extensions-expose-autojoin-own-channel-SNAPSHOT.jar",
          "size": 50204,
          "sha512": "59dfeedc4652f5896117487a1dbc2dcef8723a07a56abeaedd9ac3ab15b2b4e15c9f33fd63a2d19971b9abdf70cb8d8fa912696c01bb90a69f870c98ba83d802",
          "sha256": "b17c1343380e912f4cc986777bf4b93b618e94005563930f15ae4e34fc3258e7",
          "sha1": "4af18a18ca1dcf8c2f3b37cd19ac6861fbc3e141",
          "md5": "633e0a71f87edd9a24e9e7f0e56745a1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "twitch4j-extensions-expose-autojoin-own-channel-SNAPSHOT-sources.jar",
          "url": "twitch4j-extensions-expose-autojoin-own-channel-SNAPSHOT-sources.jar",
          "size": 18485,
          "sha512": "437399f5ca8b8cfd1dce683ee9e64439b5167d4ec04fe1524948d4edfa13c239f3801c18a42829ca15bc4947a8b4cd713929205de90729e62cfa2d6ddd4ec09e",
          "sha256": "6f6bf5e8b1ec69e6e65d002693af45846221d0b724183aa3686d8d44c5ddea5b",
          "sha1": "3774182e7430199fdf986ec3630c53152ef9e3c9",
          "md5": "6cc182cd7c1b73e1a0e315993e6f44fb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "twitch4j-extensions-expose-autojoin-own-channel-SNAPSHOT-javadoc.jar",
          "url": "twitch4j-extensions-expose-autojoin-own-channel-SNAPSHOT-javadoc.jar",
          "size": 187851,
          "sha512": "5908688db434a5e45527bcaa770b606186fd2af51dc0e89d6952b0c302c18f6ef2890cf8df986850a30198b430f5e8e9ee5703985c6410a70f8472b4d50da6fe",
          "sha256": "f0c6195c0aea9bf9c28a1fe531ae2fa6df71c807718cbbd2b643497d8e135203",
          "sha1": "6df5dd0c9cfb196cb3453f19d6e03f0827516e94",
          "md5": "ce29c33b008775e05f9f57c048ce02d8"
        }
      ]
    }
  ]
}
