{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.pblop",
    "module": "twitch4j",
    "version": "expose-autojoin-own-channel-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        },
        {
          "group": "commons-configuration",
          "module": "commons-configuration",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "com.bucket4j",
          "module": "bucket4j_jdk8-core",
          "version": {
            "requires": "8.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.philippheuer.credentialmanager",
          "module": "credentialmanager",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-slf4j",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-okhttp",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-hystrix",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "com.neovisionaries",
          "module": "nv-websocket-client",
          "version": {
            "requires": "2.14"
          }
        },
        {
          "group": "com.github.tony19",
          "module": "named-regexp",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.netflix.hystrix",
          "module": "hystrix-core",
          "version": {
            "requires": "1.5.18"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.19.0"
          }
        },
        {
          "group": "io.github.xanthic.cache",
          "module": "cache-bom",
          "version": {
            "requires": "0.7.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.github.philippheuer.events4j",
          "module": "events4j-bom",
          "version": {
            "requires": "0.12.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.20.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-auth",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-chat",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-client-websocket",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-common",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-eventsub-common",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-eventsub-websocket",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-extensions",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-graphql",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-helix",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-kraken",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-messaginginterface",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-pubsub",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-util",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "io.github.xanthic.cache",
          "module": "cache-provider-caffeine"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        },
        {
          "group": "com.github.tony19",
          "module": "named-regexp"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-slf4j",
          "version": {
            "requires": "13.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-okhttp",
          "version": {
            "requires": "13.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson",
          "version": {
            "requires": "13.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-hystrix",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "files": [
        {
          "name": "twitch4j-expose-autojoin-own-channel-SNAPSHOT.jar",
          "url": "twitch4j-expose-autojoin-own-channel-SNAPSHOT.jar",
          "size": 90803,
          "sha512": "3b391d3b93ba86f25954f437c8a12780563de9e0c3da6960a40860e3f49282e8430c81903e08b26866301416ec72c55958bcdb3279fd119b0b3a86636ef70bb4",
          "sha256": "24667fdc5d685f388854f634db5b0fc14043ca7cd4f85795e70e5e357ad15442",
          "sha1": "3ea49121393a688b4e7f457040fc339d7be34a71",
          "md5": "9ef4c5437eada0c01283a2e5a6330fbb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        },
        {
          "group": "commons-configuration",
          "module": "commons-configuration",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "com.bucket4j",
          "module": "bucket4j_jdk8-core",
          "version": {
            "requires": "8.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.philippheuer.credentialmanager",
          "module": "credentialmanager",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-slf4j",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-okhttp",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-hystrix",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "com.neovisionaries",
          "module": "nv-websocket-client",
          "version": {
            "requires": "2.14"
          }
        },
        {
          "group": "com.github.tony19",
          "module": "named-regexp",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.netflix.hystrix",
          "module": "hystrix-core",
          "version": {
            "requires": "1.5.18"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.19.0"
          }
        },
        {
          "group": "io.github.xanthic.cache",
          "module": "cache-bom",
          "version": {
            "requires": "0.7.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.github.philippheuer.events4j",
          "module": "events4j-bom",
          "version": {
            "requires": "0.12.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.20.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-auth",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-chat",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-client-websocket",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-common",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-eventsub-common",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-eventsub-websocket",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-extensions",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-graphql",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-helix",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-kraken",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-messaginginterface",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-pubsub",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-util",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "io.github.xanthic.cache",
          "module": "cache-provider-caffeine"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind"
        },
        {
          "group": "com.github.tony19",
          "module": "named-regexp"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-slf4j",
          "version": {
            "requires": "13.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-okhttp",
          "version": {
            "requires": "13.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson",
          "version": {
            "requires": "13.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-hystrix",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "files": [
        {
          "name": "twitch4j-expose-autojoin-own-channel-SNAPSHOT.jar",
          "url": "twitch4j-expose-autojoin-own-channel-SNAPSHOT.jar",
          "size": 90803,
          "sha512": "3b391d3b93ba86f25954f437c8a12780563de9e0c3da6960a40860e3f49282e8430c81903e08b26866301416ec72c55958bcdb3279fd119b0b3a86636ef70bb4",
          "sha256": "24667fdc5d685f388854f634db5b0fc14043ca7cd4f85795e70e5e357ad15442",
          "sha1": "3ea49121393a688b4e7f457040fc339d7be34a71",
          "md5": "9ef4c5437eada0c01283a2e5a6330fbb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "twitch4j-expose-autojoin-own-channel-SNAPSHOT-sources.jar",
          "url": "twitch4j-expose-autojoin-own-channel-SNAPSHOT-sources.jar",
          "size": 43738,
          "sha512": "747da64b140af80fe317e95e3f6aced9e408dc24308bfc7762e9e99e949f58c401fd04072cf80f9151eff0c8c9a780d51b457a22f3aa39a9ab11cac0a74af34c",
          "sha256": "2b5254362787d65f8fabcdefdcbdcc81cd0f6341de7289c534077f941a95afc6",
          "sha1": "05e159e4ca5ab397dfea3d197d03bc72f5a3a17a",
          "md5": "56ea5d904c414ad300dde5873b8a8899"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "twitch4j-expose-autojoin-own-channel-SNAPSHOT-javadoc.jar",
          "url": "twitch4j-expose-autojoin-own-channel-SNAPSHOT-javadoc.jar",
          "size": 236520,
          "sha512": "dc3d62c6bf9d94f66918a5cdad2e8322c99888c7b17c527840d53635f58262029289264a13b83de68a3d9e721887f538e61dda027d68479f38a7496a96cd0f47",
          "sha256": "737aa54bf44c4c8eef0aafd9fb2113f142dbc2008cb15c3fecc11b1deeca038d",
          "sha1": "a6aef308c57564924f022dd40d8e0d57941adcc3",
          "md5": "118b7bc2e6759840dc6de770648c7dd3"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "twitch4j-expose-autojoin-own-channel-SNAPSHOT-all.jar",
          "url": "twitch4j-expose-autojoin-own-channel-SNAPSHOT-all.jar",
          "size": 17616897,
          "sha512": "1573d897c6ea45e536678b5f775123553409ff709e260e6ac3e9885fcda544132ff1df1d599c09eb235b0c24d899e407bb194f7bddc916264cb60cb6cb9319c3",
          "sha256": "7a711a8c5c9b70b8da52191b2089abb8183840a5f756ab05b7f071e79a1ec26a",
          "sha1": "05192e87748fb8077213695a2c9ddcb303d0e9c0",
          "md5": "5d6c3f99a6f39077637b523059a8e96d"
        }
      ]
    }
  ]
}
