{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.pblop",
    "module": "twitch4j-common",
    "version": "expose-autojoin-own-channel-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        },
        {
          "group": "commons-configuration",
          "module": "commons-configuration",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "com.bucket4j",
          "module": "bucket4j_jdk8-core",
          "version": {
            "requires": "8.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.philippheuer.credentialmanager",
          "module": "credentialmanager",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-slf4j",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-okhttp",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-hystrix",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "com.neovisionaries",
          "module": "nv-websocket-client",
          "version": {
            "requires": "2.14"
          }
        },
        {
          "group": "com.github.tony19",
          "module": "named-regexp",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.netflix.hystrix",
          "module": "hystrix-core",
          "version": {
            "requires": "1.5.18"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.19.0"
          }
        },
        {
          "group": "io.github.xanthic.cache",
          "module": "cache-bom",
          "version": {
            "requires": "0.7.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.github.philippheuer.events4j",
          "module": "events4j-bom",
          "version": {
            "requires": "0.12.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.20.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.github.philippheuer.events4j",
          "module": "events4j-core"
        },
        {
          "group": "com.github.philippheuer.events4j",
          "module": "events4j-handler-simple"
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310"
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-auth",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-util",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-slf4j",
          "version": {
            "requires": "13.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-okhttp",
          "version": {
            "requires": "13.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson",
          "version": {
            "requires": "13.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-hystrix",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "files": [
        {
          "name": "twitch4j-common-expose-autojoin-own-channel-SNAPSHOT.jar",
          "url": "twitch4j-common-expose-autojoin-own-channel-SNAPSHOT.jar",
          "size": 67658,
          "sha512": "96de700bd6abe9bf2b64a859c1710194a56665b88f4bb77aaaf5b5dffd56fc2217bf34f28611d494691db01f954ecabdcabc1c865449933b21a283cc9b1f960f",
          "sha256": "a2500c86c8cc71a1f039ed1880d6a61de82943700f5fbff3944f86d42ac6246f",
          "sha1": "e7592f3ac45c7dcf39e659eb97f6a1a6ef232733",
          "md5": "ad263ee365d0e656e4c28275ebdd2491"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          }
        },
        {
          "group": "commons-configuration",
          "module": "commons-configuration",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "com.bucket4j",
          "module": "bucket4j_jdk8-core",
          "version": {
            "requires": "8.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.philippheuer.credentialmanager",
          "module": "credentialmanager",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-slf4j",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-okhttp",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-hystrix",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "com.neovisionaries",
          "module": "nv-websocket-client",
          "version": {
            "requires": "2.14"
          }
        },
        {
          "group": "com.github.tony19",
          "module": "named-regexp",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.netflix.hystrix",
          "module": "hystrix-core",
          "version": {
            "requires": "1.5.18"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.19.0"
          }
        },
        {
          "group": "io.github.xanthic.cache",
          "module": "cache-bom",
          "version": {
            "requires": "0.7.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.github.philippheuer.events4j",
          "module": "events4j-bom",
          "version": {
            "requires": "0.12.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.20.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.github.philippheuer.events4j",
          "module": "events4j-core"
        },
        {
          "group": "com.github.philippheuer.events4j",
          "module": "events4j-handler-simple"
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310"
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-auth",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        },
        {
          "group": "com.github.pblop",
          "module": "twitch4j-util",
          "version": {
            "requires": "expose-autojoin-own-channel-SNAPSHOT"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "strictly": "[2.15,3-alpha[",
            "requires": "[2.15,3-alpha[",
            "prefers": "2.20.1"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-slf4j",
          "version": {
            "requires": "13.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-okhttp",
          "version": {
            "requires": "13.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson",
          "version": {
            "requires": "13.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-hystrix",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "files": [
        {
          "name": "twitch4j-common-expose-autojoin-own-channel-SNAPSHOT.jar",
          "url": "twitch4j-common-expose-autojoin-own-channel-SNAPSHOT.jar",
          "size": 67658,
          "sha512": "96de700bd6abe9bf2b64a859c1710194a56665b88f4bb77aaaf5b5dffd56fc2217bf34f28611d494691db01f954ecabdcabc1c865449933b21a283cc9b1f960f",
          "sha256": "a2500c86c8cc71a1f039ed1880d6a61de82943700f5fbff3944f86d42ac6246f",
          "sha1": "e7592f3ac45c7dcf39e659eb97f6a1a6ef232733",
          "md5": "ad263ee365d0e656e4c28275ebdd2491"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "twitch4j-common-expose-autojoin-own-channel-SNAPSHOT-sources.jar",
          "url": "twitch4j-common-expose-autojoin-own-channel-SNAPSHOT-sources.jar",
          "size": 35531,
          "sha512": "8b547e0eb50b30515b996fbfaae7772266ccbb173045dedb57e03ad850c97d1ad604b49e3962f87df59aa5f1ee3eb843eaf246c788378f42902cdc0b839c8354",
          "sha256": "ac5780d67db902e594eb5e48b07996c795d6e843bc50722337676a9a607f8f38",
          "sha1": "a8a98404065503e296b6513ddd560cae1875aa90",
          "md5": "1ff33365899242d008c894c2487503c9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "twitch4j-common-expose-autojoin-own-channel-SNAPSHOT-javadoc.jar",
          "url": "twitch4j-common-expose-autojoin-own-channel-SNAPSHOT-javadoc.jar",
          "size": 313321,
          "sha512": "648d9afab318ba061ed6b144172dfa87b444a3f621469c486e9dedc9eb1f950a36de343a684b4d4709a600928638b2497f9abb129aa2ad329827ad850e4984d0",
          "sha256": "e1ff605dcb4e3b8bfebed839cc2d3ee875a175790f42f3a036241855c6f555e5",
          "sha1": "7f52da1ca26aa43c0c21e791eacde223dc607815",
          "md5": "8b17002dfe578734e95ac5b37a529e82"
        }
      ]
    }
  ]
}
